schema_version = "1.0.0"
id = "omni_outset"
version = "1.0.0"
name = "OmniOutset"
tagline = "Smart face normal extrusion with boundary outset and equidistant edge extrusion."
maintainer = "ZXY"
type = "add-on"
blender_version_min = "4.2.0"
license = [
    "SPDX-License-Identifier: GPL-2.0-or-later"
]