schema_version = "1.0.0"
id = "omni_outset"
version = "1.1.1"
name = "OmniOutset"
tagline = "Smart Face and Equidistant Edge Extrude"
maintainer = "ZXY"
type = "add-on"
website = "https://extensions.blender.org/add-ons/omnioutset/"
tags = ["Modeling"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]